---
- name: Generate password for VNC user {{ item.username }}
  set_fact:
    "vnc_password_{{ item.username }}": "{{ lookup('community.general.random_string', length=8, special=false) }}"
- name: Add generated VNC user password to Secret Manager
  google.cloud.gcp_secret_manager:
    name: "vnc-server-password-{{ item.username }}-{{ cluster_name }}-{{ cluster_id }}"
    auth_kind: machineaccount
    state: present
    project: "{{ gcp_project_id }}"
    value: "{{ vars['vnc_password_' + item.username] }}"
