---
- name: Create vdi user group {{ vdi_user_group }} if it does not exist
  group:
    name: "{{ vdi_user_group }}"
    state: present

- name: Create VDI users from guac_map
  include_tasks: create_vdi_user.yaml
  loop: "{{ guac_map }}"
  loop_control:
    loop_var: item
