---
- name: Gather distribution facts
  ansible.builtin.setup:
    gather_subset: platform

- name: Set package manager and desktop-packages
  ansible.builtin.set_fact:
    # pkg_mgr: "{{ 'yum' if ansible_facts.os_family == 'RedHat' else 'apt' }}"
    gui_packages: >-
      {{ 
        ['@Xfce','@base-x'] 
          if ansible_facts.os_family == 'RedHat' 
        else 
        ['xfce4','xserver-xorg-core'] 
      }}
    vnc_pkg: >-
      {%- if vnc_flavor|lower == 'tigervnc' and ansible_facts.os_family == 'RedHat' -%}
      tigervnc-server
      {%- elif vnc_flavor|lower == 'tigervnc' -%}
      tigervnc-standalone-server
      {%- elif vnc_flavor|lower == 'tightvnc' and ansible_facts.os_family == 'RedHat' -%}
      tightvnc-server
      {%- else -%}
      tightvnc-standalone-server
      {%- endif %}

- name: Update repository cache & install EPEL (RedHat only)
  ansible.builtin.package:
    name: epel-release
    state: present
    update_cache: yes
  when: ansible_facts.os_family == 'RedHat'
  retries: 10
  delay: 3

- name: Install desktop prerequisites & VNC package
  ansible.builtin.package:
    name: "{{ gui_packages + [vnc_pkg] }}"
    state: present
  retries: 10
  delay: 3

- name: Ensure requests package is installed
  pip:
    name: requests
    state: present

- name: Ensure Python & tooling are installed
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - jq
    state: present
