
---
# Per-user configuration
- name: Configure per-user VNC settings
  include_tasks: vnc_user_config.yaml
  loop: "{{ vdi_users_updated }}"
  loop_control:
    loop_var: item
  vars:
    vnc_password: "{{ item.password }}"

# Global VNC users mapping (for systemd service)
- name: Template TigerVNC users file
  ansible.builtin.template:
    src: vncserver.users.j2
    dest: /etc/tigervnc/vncserver.users
    mode: '0644'
  vars:
    guac_map: "{{ vdi_users_updated }}"

# Systemd unit
- name: Deploy vncserver@.service unit file
  ansible.builtin.copy:
    src: vncserver@.service
    dest: /etc/systemd/system/vncserver@.service
    mode: '0644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

# Enable & start each user's VNC server
- name: Enable & start TigerVNC instances for each user
  ansible.builtin.systemd:
    name: "vncserver@:{{ item.port | int - 5900 }}"
    enabled: yes
    state: started
  loop: "{{ vdi_users_updated }}"
  loop_control:
    loop_var: item
