---
# General secret handling
- name: Generate password for the VDI server webapp admin user
  set_fact:
    webapp_admin_password: "{{ lookup('community.general.random_string', length=8, special=false) }}"
- name: Create a GCP secret for webapp server login
  google.cloud.gcp_secret_manager:
    name: "webapp-server-password-{{ deployment_name }}"
    auth_kind: machineaccount
    state: present
    project: "{{ secret_manager_project }}"
    value: "{{ webapp_admin_password }}"
  register: webapp_secret
- name: Compute Webapp admin password hash to save to Webapp server
  set_fact:
    webapp_admin_hash: "{{ webapp_admin_password | hash('sha256') | upper }}"

- name: Generate random password used for webapp database
  set_fact:
    database_password: "{{ lookup('community.general.random_string', length=32, special=false) }}"
- name: Add generated database password to Secret Manager
  google.cloud.gcp_secret_manager:
    name: "db-password-{{ deployment_name }}"
    auth_kind: machineaccount
    state: present
    project: "{{ secret_manager_project }}"
    value:  "{{ database_password }}"
  register: database_secret

# Per-user secret handling
- name: Generate per-user secrets and enrich list
  include_tasks: user_secret_tasks.yaml
  loop: "{{ vdi_users }}"
  loop_control:
    loop_var: item

- name: Overwrite vdi_users with enriched list
  ansible.builtin.set_fact:
    vdi_users: "{{ vdi_users_updated }}"
  when: vdi_users_updated is defined
