---
- name: Compute default secret_name if none provided
  set_fact:
    secret_name: "vdi-user-password-{{ item.username }}-{{ deployment_name }}"
  when:
    - item.password is not defined
    - item.secret_name is not defined

- name: Decide password source for {{ item.username }}
  set_fact:
    password_source: >-
      {%- if item.password is defined -%}blueprint
      {%- elif item.secret_name is defined -%}secret
      {%- else -%}generate{%- endif -%}

- name: Fetch existing Secret-Manager password
  google.cloud.gcp_secret_manager:
    name:  "{{ item.secret_name }}"
    auth_kind: machineaccount
    project: "{{ project_id }}"
    state: present
  register: sm_result
  failed_when: false
  when: password_source | trim  == "secret"

- name: Use SM secret if we got one
  set_fact:
    vdiuser_password: "{{ sm_result.value }}"
  when:
    - password_source  == "secret"
    - sm_result.value is defined

- name: Use blueprint password
  set_fact:
    vdiuser_password: "{{ item.password }}"
  when: password_source  == "blueprint"

- name: Generate a new random password
  set_fact:
    vdiuser_password: "{{ lookup('ansible.builtin.password','/dev/null',length=12, chars=['ascii_letters']) }}"
  when: password_source  == "generate"

- name: Store generated password in Secret Manager
  google.cloud.gcp_secret_manager:
    name:  "{{ item.secret_name | default(secret_name) }}"
    auth_kind: machineaccount
    project: "{{ project_id }}"
    state: present
    value: "{{ vdiuser_password }}"
  when: password_source  == "generate"

- name: Build enriched user list
  ansible.builtin.set_fact:
    vdi_users_updated: >-
      {{
        (vdi_users_updated | default([]))
        + [ item | combine({ 'password': vdiuser_password }) ]
      }}
