---
- name: Get default Python interpreter from update-alternatives
  ansible.builtin.shell: >
    /usr/sbin/update-alternatives --display python3 |
    grep 'link currently points to' |
    awk '{print $NF}'
  register: default_python
  changed_when: false

- name: Get Guac' user / port mapping
  ansible.builtin.set_fact:
    guac_map: "{{ ansible_local.ghpcfe.config.guac_user_port_map | default([]) }}"

- name: Set default Python interpreter for Ansible
  ansible.builtin.set_fact:
    ansible_python_interpreter: "{{ default_python.stdout }}"

- name: Verify Python interpreter
  ansible.builtin.command: "{{ ansible_python_interpreter }} --version"
  register: python_version

- name: Display Python version
  ansible.builtin.debug:
    msg: "The Python interpreter version is: {{ python_version.stdout }}"

- name: Ensure requests library is present
  pip:
    name:
      - requests
      - passlib
    state: present
  retries: 10
  delay: 3

- name: Ensure jq is present
  package:
    name: jq
    state: present
  retries: 10
  delay: 3

- name: Get project ID from metadata
  uri:
    url: "http://metadata.google.internal/computeMetadata/v1/project/project-id"
    method: GET
    return_content: yes
    headers:
      Metadata-Flavor: Google
  register: project_id_response
  failed_when: project_id_response.status != 200
- name: Set fact for GCP project ID
  set_fact:
    gcp_project_id: "{{ project_id_response.content }}"

- name: Create vdi user group {{ vdi_user_group }} if it does not exist
  group:
    name: "{{ vdi_user_group }}"
    state: present

- name: Generate per-user VNC passwords and create GCP secrets
  include_tasks: generate_vnc_password.yaml
  loop: "{{ guac_map }}"
  loop_control:
    loop_var: item

- name: Generate password for the Guacamole webserver admin user
  set_fact:
    guacamole_admin_password: "{{ lookup('community.general.random_string', length=8, special=false) }}"
- name: Create a GCP secret for Guacamole server login
  google.cloud.gcp_secret_manager:
    name: "guacamole-server-password-{{ cluster_name }}-{{ cluster_id }}"
    auth_kind: machineaccount
    state: present
    project: "{{ gcp_project_id }}"
    value: "{{ guacamole_admin_password }}"
  register: guacserver_secret
- name: Compute Guacamole admin password hash to save to Guacserver
  set_fact:
    guacadmin_hash: "{{ guacamole_admin_password | hash('sha256') | upper }}"

- name: Generate random password used for Guacamole database
  set_fact:
    database_password: "{{ lookup('community.general.random_string', length=32, special=false) }}"
- name: Add generated database password to Secret Manager
  google.cloud.gcp_secret_manager:
    name: "db-password-{{ cluster_name }}-{{ cluster_id }}"
    auth_kind: machineaccount
    state: present
    project: "{{ gcp_project_id }}"
    value:  "{{ database_password }}"
  register: database_secret
