---
- name: Ensure VNC configuration directory exists
  file:
    path: "/home/{{ item.username }}/.vnc"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ vdi_user_group }}"
    mode: '0700'

- name: Set VNC password for {{ item.username }}
  become_user: "{{ item.username }}"
  shell: |
    echo "{{ vnc_password }}" | vncpasswd -f > "/home/{{ item.username }}/.vnc/passwd"
    chmod 600 "/home/{{ item.username }}/.vnc/passwd"

- name: Copy per-user VNC config
  template:
    src: config.j2
    dest: "/home/{{ item.username }}/.vnc/config"
    owner: "{{ item.username }}"
    group: "{{ vdi_user_group }}"
    mode: '0644'